pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/priyadarshi123/GITMASTER.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-python-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8501:8501 my-python-app'
            }
        }
    }
}